version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  github-cli: circleci/github-cli@2.1.0
  slack: circleci/slack@4.1.3

parameters:
  sbt_version:
    type: string
    default: "1.8.0"

executors:
  main-docker-executor:
    docker:
      - image: cimg/openjdk:11.0-node

context: &context
  - insight-engine-cicd
  - shared-datadog-token
  - shared-gemfury-tokens
  - shared-github-token
  - shared-sonarcloud-token

defaults-paramatetr-job: &defaults-paramatetr-job
  executor: main-docker-executor

commands:
  docker-compose-up:
    description: Setup Docker
    steps:
      - run:
          name: Start Docker Compose
          command: |
            echo ${GITHUB_TOKEN} | docker login ghcr.io -u "$GITHUB_EMAIL" --password-stdin

            LOCAL_DEV=FALSE docker-compose -f .devcontainer/docker-compose.yml up -d --build

            docker ps

            docker exec $(docker ps -aqf "name=devcontainer-main-1") bash -l -c -i "mkdir /tmp/data ;cp -R /workspace/* /workspace/.[^.]* /tmp/data > /dev/null"
  sbt-setup:
    steps:
      - run:
          name: Sbt setup
          command: |
            cd $HOME

            curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup -q -y
  scala-build:
    steps:
      - run:
          name: Build jar
          command: |
            docker exec $(docker ps -aqf "name=devcontainer-main-1") bash -l -c -i "cd /tmp/data; ./scripts/build.sh"
  scala-test:
    description: Test execution
    steps:
      - run:
          name: Execute tests
          command: |
            docker exec $(docker ps -aqf "name=devcontainer-main-1") bash -l -c -i "cd /tmp/data; ./scripts/test.sh"
  configure-git:
    steps:
      - run:
          name: Configure Git
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "$GITHUB_EMAIL"
            git config user.name "CircleCI"

            git remote set-url origin "https://${GITHUB_TOKEN}@github.com/syngenta-digital/${CIRCLE_PROJECT_REPONAME}.git"
  aws-profiles:
    steps:
      - run:
          name: Setup AWS profiles
          command: |
            npx @syngenta-digital/acp --file $(pwd)/aws/profiles.yml

            sudo apt update
            sudo apt install -y less

            aws sts get-caller-identity

            cat ~/.aws/config
            printenv
  scala-release:
    parameters:
      release_type:
        type: string
    steps:
      - run:
          name: Swith to main branch
          command: |
            bash scripts/common/utils_switch_to_main_or_master.sh
      - run:
          name: Publish release
          command: |
            RELEASE_TYPE=$(echo "<<parameters.release_type>>" | sed 's/^version-//g' | sed -rn 's/(patch|minor|major)$/\1/p')

            # Exit if is not a release commit
            if [[ -z "$RELEASE_TYPE" ]]; then
              echo "Skipping release"

              exit 0
            fi

            sbt bump-$RELEASE_TYPE
jobs:
  perform-qa:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: large
    steps:
      - checkout
      - docker-compose-up
      - scala-build
      - scala-test
  release:
    <<: *defaults-paramatetr-job
    parameters:
      release_type:
        type: string
        default: ""
    steps:
      - checkout
      - sbt-setup
      - configure-git
      - scala-release:
          release_type: "<<parameters.release_type>>"
workflows:
  release:
    when:
      or:
        - equal: ["version-patch", "<<pipeline.git.tag>>"]
        - equal: ["version-minor", "<<pipeline.git.tag>>"]
        - equal: ["version-major", "<<pipeline.git.tag>>"]
    jobs:
      - release:
          context: *context
          release_type: "<<pipeline.git.tag>>"
  main:
    jobs:
      - perform-qa:
          context: *context
