name: "Build DevContainer image"

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - main
      - master
    paths:
      - .devcontainer/**
      - pyproject.toml
      - poetry.lock
      - build.gradle
jobs:
  call-workflow-passing-data:
    uses: syngenta-digital/script-shell-data-pipelines-orb/.github/workflows/devcontainer.yaml@main
    with: {}
    secrets:
      _github_token: ${{ secrets.GITHUB_TOKEN }}
      _fury_auth: ${{ secrets.FURY_AUTH }}
